name: indexed_list_view
description: Infinite ListView that lets you programmatically jump instantly to any item, by index. Performant for lists of any size.
version: 1.1.5
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/indexed_list_view

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
